apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQxMjM=      # "password123"
  mysql-user: Zmxhc2thcHA=                  # "flaskapp"
  mysql-password: Zmxhc2thcHA=              # "flaskapp"
  mysql-database: ZXhhbXBsZURi              # "exampleDb"
