apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3JkMTIz
  mysql-database: ZXhhbXBsZURi
  mysql-user: Zmxhc2thcHA=
  mysql-password: Zmxhc2thcHA=
