apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3JkMTIz        # rootpassword123
  mysql-user: Zmxhc2thcHA=                         # flaskapp
  mysql-password: Zmxhc2thcHA=                     # flaskapp
  mysql-database: ZXhhbXBsZURi                     # exampleDb
